### ISSUE TITLE
Question: how to do `__in` queries?

### ISSUE THREAD

**Issue by codekiln** [barseghyanartur/django-mongoengine-filter#11]
For a document that contains a field with choices: 

```python
class UploadJob(Document):
    status = StringField(choices=(("queued", "Queued"), ("in_progress", "In Progress"), ("completed", "Completed"))) 
```

What is the preferred method of finding `UploadJob.objects.filter(status__in=['queued', 'in_progress'])` using this library?

Currently, if I submit a `QueryDict` with `?status='in_progress'&status='queued'`, it resolves to `status[]`, which is not picked up by Django filter as an `__in` query.

**Comment by barseghyanartur** [comment]
You should use [MultipleChoiceFilter](https://github.com/barseghyanartur/django-mongoengine-filter/blob/master/django_mongoengine_filter/filters.py#L138).
