### ISSUE TITLE
ImportError: cannot import name 'ugettext' from 'django.utils.translation'

### ISSUE THREAD

**Issue by basitiyidir** [barseghyanartur/django-mongoengine-filter#14]
It was removed in django 4.
How we can solve this problem.

https://stackoverflow.com/questions/71420362/django4-0-importerror-cannot-import-name-ugettext-lazy-from-django-utils-tra

**Comment by barseghyanartur** [comment]
@basitiyidir:

You could submit a PR.

**Comment by basitiyidir** [comment]
I've been using Django 3 and django-mongoengine-filter for over a year.
I upgraded the app to Django 4.
The following error is coming.

I need to find a way to solve this. Because my whole project is affected.

<img width="1122" alt="f" src="https://user-images.githubusercontent.com/1632765/169859253-d33b7534-b129-469b-9a9d-d0cbcb7efc9e.png">

**Comment by barseghyanartur** [comment]
It's WIP in branch [0.4.x](https://github.com/barseghyanartur/django-mongoengine-filter/tree/0.4.x)

**Comment by basitiyidir** [comment]
everything is fine.

Thank you.
