### ISSUE TITLE
Is it possible update this package to use Django 4.0?

### ISSUE THREAD

**Issue by ghost** [barseghyanartur/django-mongoengine-filter#15]
`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' `
`Import error 'force_text' from 'django.utils.encoding'`

These problems occured by changing version of Django to 4.1.2, because these imports are differents.

**Comment by oussjarrousse** [comment]
Let's fix it and create a pull request. What do you think?

**Comment by barseghyanartur** [comment]
Released in 0.4.0.
