### ISSUE TITLE
AttributeError: 'BaseFilterSet' object has no attribute 'is_valid'

### ISSUE THREAD

**Issue by jesusch** [barseghyanartur/django-mongoengine-filter#8]
see: https://github.com/carltongibson/django-filter/blob/master/django_filters/filterset.py#L208

Locally I fixed it by just adding
```
    def is_valid(self):
        return True
```

**Comment by jesusch** [comment]
which is not nice... I know

**Comment by barseghyanartur** [comment]
For the reference, work on this is done in [sync-api](https://github.com/barseghyanartur/django-mongoengine-filter/tree/sync-api) branch.

I applied some changes to the code, yet untested though. Any help here is appreciated.

**Comment by oussjarrousse** [comment]
I think I can provide a pull-request for this shortly.

**Comment by oussjarrousse** [comment]
@barseghyanartur. I created a pull request that addresses this issue, and added a test for the new function is_valid() and also for FilterBoolean because the pipeline was not passing due to a decrease in coverage %. The newly added test improved coverage and the pipeline is passing (win + win)

**Comment by barseghyanartur** [comment]
Released in 0.4.2.
